// automatically generated by the FlatBuffers compiler, do not modify

package viewer3d.actions.websocketprotocol;

public final class ContentType {
  private ContentType() { }
  public static final byte None = 0;
  public static final byte Text = 1;
  public static final byte Json = 2;
  public static final byte Blob = 3;
  public static final byte ArrayBuffer = 4;

  public static final String[] names = { "None", "Text", "Json", "Blob", "ArrayBuffer", };

  public static String name(int e) { return names[e]; }
}

