// automatically generated by the FlatBuffers compiler, do not modify

package viewer3d.actions.websocketprotocol;

public final class MessageType {
  private MessageType() { }
  public static final byte Request = 0;
  public static final byte Response = 1;
  public static final byte Publish = 2;
  public static final byte Subscription = 3;

  public static final String[] names = { "Request", "Response", "Publish", "Subscription", };

  public static String name(int e) { return names[e]; }
}

