// automatically generated by the FlatBuffers compiler, do not modify

package viewer3d.actions.websocketprotocol;

public final class MessageFlags {
  private MessageFlags() { }
  public static final byte None = 0;
  public static final byte Authentication = 1;
  public static final byte Welcome = 2;
  public static final byte Error = 4;
  public static final byte Cancel = 8;
  public static final byte MultiPart = 16;
  public static final byte Complete = 32;
  public static final byte Streaming = 64;
}

