// automatically generated by the FlatBuffers compiler, do not modify

package viewer3d.actions.websocketprotocol;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class MutiPartMessageContent extends Table {
  public static MutiPartMessageContent getRootAsMutiPartMessageContent(ByteBuffer _bb) { return getRootAsMutiPartMessageContent(_bb, new MutiPartMessageContent()); }
  public static MutiPartMessageContent getRootAsMutiPartMessageContent(ByteBuffer _bb, MutiPartMessageContent obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public MutiPartMessageContent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public MessageContent body(int j) { return body(new MessageContent(), j); }
  public MessageContent body(MessageContent obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int bodyLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createMutiPartMessageContent(FlatBufferBuilder builder,
      int bodyOffset) {
    builder.startObject(1);
    MutiPartMessageContent.addBody(builder, bodyOffset);
    return MutiPartMessageContent.endMutiPartMessageContent(builder);
  }

  public static void startMutiPartMessageContent(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addBody(FlatBufferBuilder builder, int bodyOffset) { builder.addOffset(0, bodyOffset, 0); }
  public static int createBodyVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startBodyVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endMutiPartMessageContent(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

