// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} viewerName
 * @param {string} partName
 * @param {Big} scaleX
 * @param {Big} scaleY
 * @param {Big} scaleZ
 * @returns {Promise.<void>}
 */
export async function ScalePart(viewerName, partName, scaleX, scaleY, scaleZ) {
	// BEGIN USER CODE
	const viewer = await mx.viewer3D.getViewerByName(viewerName);
	const instances = viewer.getInstancesByName(partName);
	
	_scalePart(instances, scaleX, scaleY, scaleZ);

	function _scalePart(instances, scaleX, scaleY, scaleZ) {
		if (instances && instances.length > 0) {
			instances.forEach(function(instance){
				instance.setScale(scaleX.toNumber(), scaleY.toNumber(), scaleZ.toNumber());
			});
		}
	}
	// END USER CODE
}
