// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} viewerName
 * @param {string} partName
 * @param {Big} translationX
 * @param {Big} translationY
 * @param {Big} translationZ
 * @param {"Viewer3D.LengthUnit.m"|"Viewer3D.LengthUnit.cm"|"Viewer3D.LengthUnit.mm"|"Viewer3D.LengthUnit.in"|"Viewer3D.LengthUnit.ft"|"Viewer3D.LengthUnit.km"|"Viewer3D.LengthUnit.mi"} unit
 * @returns {Promise.<void>}
 */
export async function TranslatePart(viewerName, partName, translationX, translationY, translationZ, unit) {
	// BEGIN USER CODE
	const viewer = await mx.viewer3D.getViewerByName(viewerName);
	const instances = viewer.getInstancesByName(partName);

	_translatePart(instances, translationX, translationY, translationZ, unit);

	function _translatePart(instances, ranslationX, translationY, translationZ, unit) {
		if (instances && instances.length > 0) {
			instances.forEach(function(instance){
				instance.setTranslation(ranslationX, translationY, translationZ, unit);
			});
		}
	}
	// END USER CODE
}
