// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";
import * as Wot from "@node-wot/browser-bundle";

// BEGIN EXTRA CODE
const config = {
  devServer: {
    proxy: {
      //'/': 'http://localhost:8081'
      '/': 'http://153.109.130.80:8080'

    }
  }
};

console.log(config.devServer.proxy);

var servient = new Wot.Core.Servient();
servient.addClientFactory(new Wot.Http.HttpClientFactory());
var helpers = new Wot.Core.Helpers(servient);
let counterProperties = [];

async function get_td(propertyName) {
//  var addr = "http://localhost:8081/counter/";
    //var addr = "http://153.109.130.80:5000/sensor_data/";
    var addr = "http://153.109.130.89:8080/nordic-thingy/";
  let ret = "";
  try{
    const thingFactory = await servient.start();
    const td = await helpers.fetch(addr);
    let thing = await thingFactory.consume(td);
    console.log("td: " + td);
    ret = await readProperty(thing, propertyName);
    console.log("ret: " + ret);
  }
  catch(error){
        window.alert("Could not fetch TD.\n" + error);
  }
  return ret;
}

async function readProperty(thing, propertyName) {
  let td = thing.getThingDescription();
  //counterProperties = [];
  //for (let property in td.properties) {
  console.log("property: " + propertyName);
  if (td.properties.hasOwnProperty(propertyName)) {
    let res = await thing.readProperty(propertyName);
    console.log("our output: " + res.value());
    return res.value();
  } else {
    console.log("The thing doesn't have a property named " + propertyName);
    return "The thing doesn't have a property named " + propertyName;
  }
}
// END EXTRA CODE

/**
 * @param {string} propertyName
 * @returns {Promise.<string>}
 */
export async function WoTReadProperty(propertyName) {
	// BEGIN USER CODE
  return await get_td(propertyName);
	// END USER CODE
}
