// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";
import * as WoT from "@node-wot/browser-bundle";

// BEGIN EXTRA CODE
/**
 * Fetch un endpoint multi-sensor/{propertyName} et renvoie la string JSON.
 */
async function get_td(propertyName) {
  // on pointe vers la bonne propriété, qu’il s’agisse de nordicCount ou mbientCount
  const url = `http://153.109.22.167:8088/multi-sensor/properties/${propertyName}`;
  try {
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`HTTP ${response.status} – ${response.statusText}`);
    }
    const data = await response.json();
    return JSON.stringify(data);
  } catch (error) {
    window.alert("Erreur WoTReadProperty (fetch direct) :\n" + error);
    return "";
  }
}
// END EXTRA CODE

/**
 * @param {string} propertyName
 * @returns {Promise.<string>}
 */
export async function WoTReadProperty(propertyName) {
	// BEGIN USER CODE
  return await get_td(propertyName);
	// END USER CODE
}
